--- 
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: volume-mutator
  name: volume-mutator
spec:
  replicas: 1
  selector:
    matchLabels:
      app: volume-mutator
  strategy: {}
  template:
    metadata:
      labels:
        app: volume-mutator
    spec:
      volumes:
      - name: webhook-certs
        emptyDir: {}
      initContainers:
      - image: helxplatform/volume-mutator:0.0.1
        name: tooling
        command: ['./generateTLSCerts','-M']
        ## Ensure these are controlled by makefile
        env:
        - name: MUTATE_CONFIG
          value: volume-mutator
        - name: WEBHOOK_SERVICE
          value: volume-mutator-svc
        - name: WEBHOOK_NAMESPACE
          value:  default
        volumeMounts:
        - mountPath: /helx/webhook/certs
          name: webhook-certs
      containers:
      - image: helxplatform/volume-mutator:0.0.1
        name: volume-mutator
        volumeMounts:
        - mountPath: /helx/webhook/certs 
          name: webhook-certs 
          readOnly: true
        resources: {}

---

apiVersion: v1
kind: Service
metadata:
  labels:
    app: volume-mutator
  name: volume-mutator-svc
spec:
  ports:
  - port: 8443
    protocol: TCP
    targetPort: 8443
  selector:
    app: volume-mutator
status:
  loadBalancer: {}